package com.example.ingle.domain.member.enums;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum Country {

    AFGHANISTAN("Afghanistan"),
    ANGOLA("Angola"),
    AUSTRALIA("Australia"),
    AUSTRIA("Austria"),
    AZERBAIJAN("Azerbaijan"),
    BANGLADESH("Bangladesh"),
    BELGIUM("Belgium"),
    BOLIVIA("Bolivia"),
    BRAZIL("Brazil"),
    CAMBODIA("Cambodia"),
    CANADA("Canada"),
    CHILE("Chile"),
    CHINA("China"),
    COSTA_RICA("Costa Rica"),
    COTE_DIVOIRE("Côte d’Ivoire"),
    CROATIA("Croatia"),
    CZECH_REPUBLIC("Czech Republic"),
    DENMARK("Denmark"),
    DOMINICAN_REPUBLIC("Dominican Republic"),
    EGYPT("Egypt"),
    ETHIOPIA("Ethiopia"),
    FINLAND("Finland"),
    FRANCE("France"),
    GABON("Gabon"),
    GEORGIA("Georgia"),
    GERMANY("Germany"),
    GHANA("Ghana"),
    GUATEMALA("Guatemala"),
    HONDURAS("Honduras"),
    HUNGARY("Hungary"),
    INDIA("India"),
    INDONESIA("Indonesia"),
    ISRAEL("Israel"),
    ITALY("Italy"),
    JAPAN("Japan"),
    KAZAKHSTAN("Kazakhstan"),
    KYRGYZSTAN("Kyrgyzstan"),
    LAOS("Laos"),
    LATVIA("Latvia"),
    MALAYSIA("Malaysia"),
    MEXICO("Mexico"),
    MOLDOVA("Moldova"),
    MONGOLIA("Mongolia"),
    NEPAL("Nepal"),
    NETHERLANDS("Netherlands"),
    NEW_ZEALAND("New Zealand"),
    PAKISTAN("Pakistan"),
    PANAMA("Panama"),
    PARAGUAY("Paraguay"),
    PERU("Peru"),
    PHILIPPINES("Philippines"),
    POLAND("Poland"),
    PORTUGAL("Portugal"),
    ROMANIA("Romania"),
    RWANDA("Rwanda"),
    SENEGAL("Senegal"),
    SINGAPORE("Singapore"),
    SLOVENIA("Slovenia"),
    SOUTH_AFRICA("South Africa"),
    SOUTH_KOREA("South Korea"),
    SPAIN("Spain"),
    SRI_LANKA("Sri Lanka"),
    SWITZERLAND("Switzerland"),
    TAIWAN("Taiwan"),
    TANZANIA("Tanzania"),
    THAILAND("Thailand"),
    TURKEY("Turkey"),
    UKRAINE("Ukraine"),
    UNITED_ARAB_EMIRATES("United Arab Emirates"),
    UNITED_KINGDOM("United Kingdom"),
    UNITED_STATES("United States"),
    UZBEKISTAN("Uzbekistan"),
    VENEZUELA("Venezuela"),
    VIETNAM("Vietnam"),
    ZAMBIA("Zambia");

    private final String fullName;
}
