spring:
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # 파일 업로드 설정
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  jpa:
    show-sql: false
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false
        use_sql_comments: false
        type: false
        jdbc:
          time_zone: Asia/Seoul

  data:
    redis:
      host: ingle-redis
      port: 6379

oracle:
  datasource:
    jdbc-url: ${ORACLE_URL}
    username: ${ORACLE_USERNAME}
    password: ${ORACLE_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
  enabled: true

swagger:
  server-url: ${SERVER_URL}

file:
  upload-dir: ${IMAGE_PATH}

jwt:
  secret: ${JWT_SECRET}

admin:
  username: ${ADMIN_USERNAME}
  password: ${ADMIN_PASSWORD}

server:
  port: 8089

logging:
  file:
    path: /ingle/logs